apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: camera-stream-health-predictor
  namespace: ml-eagle
spec:
  predictor:
    serviceAccountName: sa-s3-access
    sklearn:
      storageUri: s3://charan-camera-stream-health-eaglesight/models/stream_failure_model.pkl
