apiVersion: v1
kind: Service
metadata:
  name: camera-stream-health-api
  namespace: camera-health
spec:
  selector:
    app: camera-stream-health-api
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
