apiVersion: v1
kind: Namespace
metadata:
  name: camera-stream-health
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: camera-stream-health
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: us-east-1
    serving.kserve.io/s3-useanoncredential: "false"
secrets:
  - name: s3-secret
